#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."

add() {
  local target="$1" file="$2"
  python3 scripts/add_sources.py "$target" "$file"
}

while IFS= read -r file; do
  add Orb "$file"
done <<'EOF'
Orb/AI/AIAnnotationViews.swift
Orb/AI/AIJobQueue.swift
Orb/AI/AIPrivacyGate.swift
Orb/AI/AIProvider.swift
Orb/AI/AISettingsView.swift
Orb/AI/AIWorker.swift
Orb/AI/DuplicateDetector.swift
Orb/AI/FactExtractor.swift
Orb/AI/RelatedItemsEngine.swift
Orb/AI/SummaryGenerator.swift
Orb/AI/TagGenerator.swift
Orb/AI/TitleGenerator.swift
Orb/Search/DocumentChunker.swift
Orb/Search/EmbeddingIndexer.swift
Orb/Search/EmbeddingProvider.swift
Orb/Search/HybridSearchMerger.swift
Orb/Search/SearchPerformanceTracer.swift
Orb/Search/SemanticQuickPasteRanker.swift
Orb/Search/VectorSearchRepository.swift
Orb/Services/CrashRecoveryService.swift
Orb/Services/DuplicateMergeFlow.swift
Orb/Services/ErrorReporter.swift
Orb/Services/IndexRebuildService.swift
Orb/Services/ItemDeletionService.swift
Orb/Services/LaunchAtLoginService.swift
Orb/Services/MenuBarController.swift
Orb/Services/PresentationModeObserver.swift
Orb/Services/ThumbnailRepairService.swift
Orb/Storage/AIAnnotationRepository.swift
Orb/Storage/JSONExportService.swift
Orb/Storage/JSONImportService.swift
Orb/Storage/MarkdownExportService.swift
Orb/Storage/MarkdownImportService.swift
Orb/Storage/MigrationV8.swift
Orb/Storage/ZIPExportService.swift
Orb/UI/BulkOrganizationView.swift
Orb/UI/ExportImportView.swift
Orb/UI/LazyBlobImageLoader.swift
Orb/UI/LibrarySearchView.swift
Orb/UI/LibraryWindow.swift
Orb/UI/OrbAnimationPolish.swift
Orb/UI/SaveToastView.swift
EOF

while IFS= read -r file; do
  add OrbTests "$file"
done <<'EOF'
OrbTests/AIAnnotationViewsTests.swift
OrbTests/AIJobQueueTests.swift
OrbTests/AIPrivacyGateTests.swift
OrbTests/AIProviderTests.swift
OrbTests/AISettingsViewTests.swift
OrbTests/AIWorkerTests.swift
OrbTests/BulkOrganizationViewTests.swift
OrbTests/CrashRecoveryServiceTests.swift
OrbTests/DocumentChunkerTests.swift
OrbTests/DuplicateDetectorTests.swift
OrbTests/DuplicateMergeFlowTests.swift
OrbTests/EmbeddingIndexerTests.swift
OrbTests/EmbeddingProviderTests.swift
OrbTests/ErrorReporterTests.swift
OrbTests/ExportImportViewTests.swift
OrbTests/FactExtractorTests.swift
OrbTests/HybridSearchMergerTests.swift
OrbTests/IndexRebuildServiceTests.swift
OrbTests/ItemDeletionServiceTests.swift
OrbTests/JSONExportServiceTests.swift
OrbTests/JSONImportServiceTests.swift
OrbTests/LaunchAtLoginServiceTests.swift
OrbTests/LazyBlobImageLoaderTests.swift
OrbTests/LibrarySearchViewTests.swift
OrbTests/LibraryWindowTests.swift
OrbTests/MarkdownExportServiceTests.swift
OrbTests/MarkdownImportServiceTests.swift
OrbTests/MenuBarControllerTests.swift
OrbTests/OrbAnimationPolishTests.swift
OrbTests/PresentationModeObserverTests.swift
OrbTests/RelatedItemsEngineTests.swift
OrbTests/SaveToastViewTests.swift
OrbTests/SearchPerformanceTracerTests.swift
OrbTests/SemanticQuickPasteRankerTests.swift
OrbTests/SummaryGeneratorTests.swift
OrbTests/TagGeneratorTests.swift
OrbTests/ThumbnailRepairServiceTests.swift
OrbTests/TitleGeneratorTests.swift
OrbTests/VectorSearchRepositoryTests.swift
OrbTests/ZIPExportServiceTests.swift
EOF

while IFS= read -r file; do
  add OrbIntegrationTests "$file"
done <<'EOF'
OrbIntegrationTests/AIAnnotationViewsIntegrationTests.swift
OrbIntegrationTests/AIJobQueueIntegrationTests.swift
OrbIntegrationTests/AIPrivacyGateIntegrationTests.swift
OrbIntegrationTests/AIProviderIntegrationTests.swift
OrbIntegrationTests/AISettingsViewIntegrationTests.swift
OrbIntegrationTests/AIWorkerIntegrationTests.swift
OrbIntegrationTests/ActivationFlowTests.swift
OrbIntegrationTests/BulkOrganizationViewIntegrationTests.swift
OrbIntegrationTests/CrashRecoveryServiceIntegrationTests.swift
OrbIntegrationTests/DocumentChunkerIntegrationTests.swift
OrbIntegrationTests/DuplicateDetectorIntegrationTests.swift
OrbIntegrationTests/DuplicateMergeFlowIntegrationTests.swift
OrbIntegrationTests/EmbeddingIndexerIntegrationTests.swift
OrbIntegrationTests/EmbeddingProviderIntegrationTests.swift
OrbIntegrationTests/ErrorReporterIntegrationTests.swift
OrbIntegrationTests/ExportImportViewIntegrationTests.swift
OrbIntegrationTests/FactExtractorIntegrationTests.swift
OrbIntegrationTests/HybridSearchMergerIntegrationTests.swift
OrbIntegrationTests/IndexRebuildServiceIntegrationTests.swift
OrbIntegrationTests/ItemDeletionServiceIntegrationTests.swift
OrbIntegrationTests/JSONExportServiceIntegrationTests.swift
OrbIntegrationTests/JSONImportServiceIntegrationTests.swift
OrbIntegrationTests/LaunchAtLoginServiceIntegrationTests.swift
OrbIntegrationTests/LazyBlobImageLoaderIntegrationTests.swift
OrbIntegrationTests/LibrarySearchViewIntegrationTests.swift
OrbIntegrationTests/LibraryWindowIntegrationTests.swift
OrbIntegrationTests/MarkdownExportServiceIntegrationTests.swift
OrbIntegrationTests/MarkdownImportServiceIntegrationTests.swift
OrbIntegrationTests/MenuBarControllerIntegrationTests.swift
OrbIntegrationTests/OrbAnimationPolishIntegrationTests.swift
OrbIntegrationTests/PresentationModeObserverIntegrationTests.swift
OrbIntegrationTests/RelatedItemsEngineIntegrationTests.swift
OrbIntegrationTests/SaveToastViewIntegrationTests.swift
OrbIntegrationTests/SearchPerformanceTracerIntegrationTests.swift
OrbIntegrationTests/SemanticQuickPasteRankerIntegrationTests.swift
OrbIntegrationTests/SummaryGeneratorIntegrationTests.swift
OrbIntegrationTests/TagGeneratorIntegrationTests.swift
OrbIntegrationTests/ThumbnailRepairServiceIntegrationTests.swift
OrbIntegrationTests/TitleGeneratorIntegrationTests.swift
OrbIntegrationTests/VectorSearchRepositoryIntegrationTests.swift
OrbIntegrationTests/ZIPExportServiceIntegrationTests.swift
EOF

echo "done"
